language: node_js
node_js:
  - '12'
git:
  depth: 3
script: 
  - yarn build
notifications:
  email:
    reciepients:
      - jossedaviid1@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: build/
  target-branch: gh-pages
  commit-message: 'deploy this proyect'
  on:
    branch: master
